name: "DPort Windows Build & Release TEST"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - run: echo "workflow registration test"
